### ISSUE TITLE
[Feat] Recruitment Detail

### ISSUE THREAD

**Issue by yeoniii20** [AriAri-Dong/ariari-frontend#14]
# Todo 🐣
> Recruitment Detail Components and Page

### components 🌴
- [x] Badge
- [x] Recruitment Card
- [x] Floating Bar
- [x] Button (Medium)
- [x] Acceptance Review Dropdown

### pages 🪐
- [x] Recruitment Detail Page

### settings ⚙️
- [x] Add Typography
- [x] Custom tailwind css

### questions 📢
1️⃣
2️⃣
