### ISSUE TITLE
[Feat] My Page - Interest Club List

### ISSUE THREAD

**Issue by yeoniii20** [AriAri-Dong/ariari-frontend#23]
# Todo 🐣
> I implemented a list screen of clubs of interest on My Page.

### components 🌴
- [x] Create radio button
- [x] Modify noti popup

### pages 🪐
- [x] Interest Club List (My Page)

### questions 📢
1️⃣
2️⃣
