### ISSUE TITLE
[Feat] Report

### ISSUE THREAD

**Issue by yeoniii20** [AriAri-Dong/ariari-frontend#35]
# Todo 🐣
> purpose

### components 🌴
- [x] report bottom seeht component
- [x] report modal component

### pages 🪐
- [x] recruitment detail page

### questions 📢
1️⃣
2️⃣
