### ISSUE TITLE
[Feat] Home Recruitment

### ISSUE THREAD

**Issue by inf0craw1** [AriAri-Dong/ariari-frontend#7]
# Todo 🐣
> Adding popular recruitment & latest recruitment to home page

### components 🌴
- [ ] Recruitment item component
- [ ] Filter tab in popular recruitment
- [ ] Slider in latest recruitment

### questions 📢

**Comment by inf0craw1** [comment]
Will work on new issues for new design
